### ISSUE TITLE
[Bug]: TablePlus and Tinkerwell not opening from Sites page

### ISSUE THREAD

**Issue by isimmons** [beyondcode/herd-community#1011]
### Platform

Windows

### Operating system version

Windows 11 Home (23H2 22631.4169)

### System architecture

Intel (x86)

### Herd Version

1.11.0

### PHP Version

PHP 8.3.11

### Bug description

When I open Herd and `Open Sites` from the Dashboard, clicking Open for TablePlus, opens Adminer in the browser. 

TablePlus is installed in the default location `"C:\Program Files\TablePlus\TablePlus.exe"`

If I go to   Services->MySql->Settings and click Open for TablePlus, it opens TablePlus with no database selected. So I guess location is not an issue.

Maybe the issue is sqlite databases?
I have no MySql databases at the moment other than the defaults for admin because my site uses sqlite.

But when opening from the site, it should open TablePlus to the sqlite database that is listed and working in TablePlus when I open it manually.

Tinkerwell also appears to not be detected from the Sites page. When I click Open, it opens powershell. I understand it may not be working yet  [this issue](https://github.com/beyondcode/herd-community/issues/542)

**Comment by mpociot** [comment]
This will be fixed in the next update

**Comment by mpociot** [comment]
This is now fixed in Herd 1.11.1

**Comment by gwillyoo** [comment]
I've just install 1.11.1, the tinkerwell still not open. How to open Herd site with tinkerwell app since i see only ssh method ?

**Comment by wishborn** [comment]
This was marked closed but I am still experiencing this issue with Tinkerwell

**Comment by Fefff** [comment]
I'm also having this issue with Herd and Tinkerwell, but only on one of my dev machines. Both are running Windows 11 too so not sure what's going on.
