### ISSUE TITLE
[Bug]: Not launching with Cursor

### ISSUE THREAD

**Issue by TheekshanaOwitiyawaththa** [beyondcode/herd-community#1358]
### Platform

Windows

### Operating system version

windows 11

### System architecture

Intel (x86)

### Herd Version

1.19.0

### PHP Version

PHP 8.4

### Bug description

![Image](https://github.com/user-attachments/assets/09ec004f-30d1-474e-beee-4d7c3fca9b13)

when i select cursor as primary editor its disabled the open button and says SublimeText does not support this feature.

### Steps to reproduce

When try to open in IDE

### Relevant log output

```shell

```

**Comment by mpociot** [comment]
This is now fixed in Herd 1.19.1

**Comment by taliesinpenbardd** [comment]
Hello,
I still have that bug.
I use Herd 1.21.2 (Build 51) on MacOS Sequoia 15.5.
In Settings > General > IDE, I chose Cursor.
When a dump() gets shown in the dump window, clicking on the line `app/Http/Livewire/Admin/Transactions/StatsTransactions.php:242` will open a window saying "No app is configured to open the URL "phpstorm://[...]"
It does work in Ignition, though.
Best regards,

![Image](https://github.com/user-attachments/assets/1ce8b00d-af2d-4478-ae6c-66cd745abc68)

![Image](https://github.com/user-attachments/assets/e338e7d5-8505-4819-84c2-50ce18ac26fd)
