### ISSUE TITLE
[Bug]: nvm installed but not recognized

### ISSUE THREAD

**Issue by SamuelNitsche** [beyondcode/herd-community#552]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0

### Bug description

Nvm was not installed on my machine prior to installing Herd. I installed it using the big red button in the "Node" tab inside Herd. I am now able to run `nvm` commands in my shell. However, Herd still wants me to install nvm using the big red button

### Steps to reproduce

Install Herd on a machine without nvm. Install nvm using Herd, restart Herd and open the "Node" Tab

**Comment by mpociot** [comment]
@SamuelNitsche This could happen if Herd is unable to detect NVM properly. Are you using a shell other than Bash/ZSH?

**Comment by SamuelNitsche** [comment]
Nope, I am using zsh with oh-my-zsh

![CleanShot 2024-03-28 at 15 24 22](https://github.com/beyondcode/herd-community/assets/24483576/31724a13-943d-4b69-ac0d-e1bc61a47bc0)

**Comment by mpociot** [comment]
This is the exact command that we run in order to read the NVM_DIR environment variable:

`/bin/zsh -l -c "[[ -f ~/.zshrc ]] && source ~/.zshrc; echo $NVM_DIR"`

The result gets trimmed.
Could this be empty for you because you have any additional shell output?

**Comment by SamuelNitsche** [comment]
That explains the issue. I had referenced an oh-my-zsh plugin which wasn't installed. This caused the following output:

![CleanShot 2024-03-28 at 15 35 22](https://github.com/beyondcode/herd-community/assets/24483576/a6a6621e-b870-4ce5-a3d8-73ac253b0a52)

**Comment by dinhquochan** [comment]
Same me, Install NVM does not response...

[output.webm](https://github.com/beyondcode/herd-community/assets/9979458/48a64f65-0fd0-4cf6-9a2d-ef21a8001691)

**Comment by SamuelNitsche** [comment]
Did you check the output of the command Marcel posted earlier?

**Comment by dinhquochan** [comment]
<img width="868" alt="image" src="https://github.com/beyondcode/herd-community/assets/9979458/60301536-aab2-43f0-a7c9-5a45996831a0">

**Comment by mpociot** [comment]
@SamuelNitsche did it work for you after cleaning the ZSH output?

**Comment by vcardillo** [comment]
I am having a similar issue:

```
$ echo $SHELL
/bin/bash
$ /bin/zsh -l -c "[[ -f ~/.zshrc ]] && source ~/.zshrc; echo $NVM_DIR"
/Users/me/Library/Application Support/Herd/config/nvm
```

Am I encountering the same issue?

**Comment by mpociot** [comment]
This fixed with Herd 1.6.0

**Comment by fboc** [comment]
> This fixed with Herd 1.6.0

I still have this issue with NVM, also after the 1.6.0 update

**Comment by MarkKnowlesR40** [comment]
Similar here, but on newer version of Herd.... **Herd 1.6.1**  //  **Sonoma 14.5** //  Settings  |  Node  |  Install NVM  (Nothing Happens)

**Comment by fboc** [comment]
> Similar here, but on a newer version of Herd.... **Herd 1.6.1** // **Sonoma 14.5** // Settings | Node | Install NVM (Nothing Happens)

Nothing happens also on **Ventura 13.6.7** with **Herd 1.6.1**.

**Comment by MarkKnowlesR40** [comment]
> @MarkKnowlesR40 which shell do you use?

It complicates things, but I switched from bash to ZSH during this. I have two machines that share the same issue. I'm not sure if this is helpful or not, but one thing they have in common is that npm and node are installed in a path that includes a "space" (...Application Support..."). See Below. Tow of my colleagues, who don't have this problem don't have a space in their paths as they installed npm before Herd.   

NODE_BINARY_FILE_PATH="/Users/xxxxxxxx/Library/Application Support/Herd/config/nvm/versions/node/v21.7.3/bin/node"
NPM_BINARY_FILE_PATH="/Users/xxxxxxxx/Library/Application Support/Herd/config/nvm/versions/node/v21.7.3/bin/npm"
