### ISSUE TITLE
[Bug]: Error with Mail feature when sending Emails (30+) within a loop

### ISSUE THREAD

**Issue by rubendn** [beyondcode/herd-community#571]
### Platform

Windows

### Operating system version

Windows 11 Pro

### System architecture

Intel (x86)

### Herd Version

1.0.1

### PHP Version

8.2.17

### Bug description

I have a loop that sends email to a # of users.  Previously for testing I was using MailGun and the emails would go out fine.
Trying the same code using the Mail feature of Herd Pro produces the following error:

`Expected response code "354" but got code "421", with message "421 Error: too many unauthenticated commands"`

It is currently producing this error with as little as 25 emails being sent in the loop.

This is the code currently being used...

```
            foreach($emailList as $email)
            {
                $emailAddress = $email->EmailAddress;
                $teamText = $this->teamText[$teamID];

                $teamText .= PHP_EOL . PHP_EOL . '----------------------------------------------------------------------' . PHP_EOL . 'This email is only sent to previous customers and persons who have signed up for new item team notifications.  If you would no longer like to receive emails from us please visit/click the following link: ' . URL::signedRoute('unsubscribe-with-email', ['email' => $emailAddress]);
                Mail::to($emailAddress)->send(new UpdateEmail($emailSubject, $emailText, $teamText));

                $emailCount ++;
                $emailsSent = $emailsSent . $emailAddress . '</br>';
                \DB::table('emailtosend')->where('EmailAddress', $emailAddress)->update(['EmailSent' => true]);
                usleep(100000); // 100ms
            }
```

**Comment by mechelon** [comment]
I was not able to reproduce this behaviour on my machine - can you share the mail-related part of your `.env` file, just to make sure that Herd Mail is set up properly?

**Comment by rubendn** [comment]
This is the mail-related part of my .env file for herd...

```
# HERD MAIL
MAIL_MAILER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_FROM_NAME="${APP_NAME}"
```

When I use MailPit with the following .env settings the code runs fine...
```
# MAILPIT
MAIL_MAILER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=1025
MAIL_FROM_NAME="${APP_NAME}"
```

Using Herd I get the error after the 2nd email in the loop.  Using MailPit or MailHog, I can send over 35 emails using the same loop without an error.

I even tested putting a 5 second delay between emails when using Herd but it still errors out after the 2nd email wit the same error each time:

`Expected response code "354" but got code "421", with message "421 Error: too many unauthenticated commands".`

**Comment by mechelon** [comment]
Have you set `MAIL_ENCRYPTION` somewhere?

**Comment by rubendn** [comment]
No, it was not set anywhere in the ENV file.   I did try it now with MAIL_ENCRYPTION=null and MAIL_ENCRYPTION=tls and the same error with both.

**Comment by rubendn** [comment]
Not sure if this is similar but this is what I found with another "fake email server" software and getting the same error:

Something to do with a setting called: maxAllowedUnauthenticatedCommands

[https://github.com/ReachFive/fake-smtp-server/issues/9](https://github.com/ReachFive/fake-smtp-server/issues/9)

**Comment by ProgramodoMeade** [comment]
I'm running into the same issue with Herd Pro.  One email sends fine, but sending multiple in a loop fails with the "too many unauthenticated commands" error.

**Comment by mpociot** [comment]
This is now fixed with Herd 1.1.0

**Comment by rockblings** [comment]
Hello, i am still experiencing this issue. my Herd version is 1.6.0. it errors out after the 2nd email. should i open a new bug report?

**Comment by mechelon** [comment]
@rockblings Can you add your details as well here: https://github.com/beyondcode/herd-community/issues/681 ?

**Comment by rockblings** [comment]
> @rockblings Can you add your details as well here: #681 ?

I have an email services that sends email to a # of users. So the emails are added to a queue, then loop over each one to send. i got the error after the 2nd email "Expected response code "354" but got code "421", with message "421 Error: too many unauthenticated commands" everytime.
here is my .env mail config

MAIL_MAILER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_FROM_NAME="${APP_NAME}"
MAIL_ENCRYPTION=tls

**Comment by rockblings** [comment]
it worked after setting the `MAIL_ENCRYPTION` to `null`

**Comment by richdynamix** [comment]
Same issue on Herd Pro 1.6.1. I have 10 users in the database and when I tried to send an email to all 10, 2 emails appear in Herd and then the UI throws the error `Expected response code "354" but got code "421", with message "421 Error: too many unauthenticated commands".`

**Comment by mpociot** [comment]
@richdynamix Do you also get this issue on Windows or are you on a mac?

**Comment by richdynamix** [comment]
@mpociot I am on a Macbook Pro (Intel). Apologies, I know it was reported on Windows, but same issue on this platform to.

**Comment by mpociot** [comment]
No worries - could you open a new issue in this case, so we don't lose track of this?
Would be great if you could provide a sample code to reproduce this - I assume a loop in a basic routes file will do?
