### ISSUE TITLE
[Bug]: curl error 23 when composer updating or installing from certain repos

### ISSUE THREAD

**Issue by glaarg-robert** [beyondcode/herd-community#662]
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.0

### Bug description

In CurlDownloader.php line 389:

  [Composer\Downloader\TransportException]
  curl error 23 while downloading https://filament-filter-sets.composer.sh/download/XXXX/advanced-tables-for-filament-3.6.15.zip: Failed writing received data to disk/application

This apparently is an issue with curl version that herd is using but herd uses its own versions of different binaries.  On a regular install apparently using brew doing a brew reinstall curl fixes the issue but when using herd this does not work.  I even went so far as to install curl with brew and placing that PATH at the start so even running a "which curl" showed the brew version of curl but that did not work either.

### Steps to reproduce

composer update

### Relevant log output

```shell
22/31 [===================>--------]  70% 2 secs  - Downloading archilex/filament-filter-sets (3.6.15)
 28/31 [=========================>--]  90% 3 secs  - Downloading archilex/filament-filter-sets (3.6.15)
 29/31 [==========================>-]  93% 6 secs  - Downloading archilex/filament-filter-sets (3.6.15)
 31/31 [============================] 100% 8 secs
In CurlDownloader.php line 389:

  [Composer\Downloader\TransportException]
  curl error 23 while downloading https://filament-filter-sets.composer.sh/download/XXXXXXX/advanced-tables-for-filament-3.6.15.zip: Failed writing received data to disk/application


Exception trace:
  at phar:///Users/robert/Library/Application Support/Herd/bin/composer/src/Composer/Util/Http/CurlDownloader.php:389
 Composer\Util\Http\CurlDownloader->tick() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/src/Composer/Util/HttpDownloader.php:392
 Composer\Util\HttpDownloader->countActiveJobs() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/src/Composer/Util/Loop.php:88
 Composer\Util\Loop->wait() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/src/Composer/Installer/InstallationManager.php:430
 Composer\Installer\InstallationManager->waitOnPromises() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/src/Composer/Installer/InstallationManager.php:286
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/src/Composer/Installer/InstallationManager.php:218
 Composer\Installer\InstallationManager->execute() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/src/Composer/Installer.php:821
 Composer\Installer->doInstall() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/src/Composer/Installer.php:646
 Composer\Installer->doUpdate() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/src/Composer/Installer.php:292
 Composer\Installer->run() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/src/Composer/Command/UpdateCommand.php:251
 Composer\Command\UpdateCommand->execute() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/src/Composer/Console/Application.php:385
 Composer\Console\Application->doRun() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/src/Composer/Console/Application.php:145
 Composer\Console\Application->run() at phar:///Users/robert/Library/Application Support/Herd/bin/composer/bin/composer:93
 require() at /Users/robert/Library/Application Support/Herd/bin/composer:29
```

**Comment by mpociot** [comment]
Can you share your composer.json so I can reproduce this locally?

**Comment by glaarg-robert** [comment]
Unfortunately this is a paid package.  I am happy to share the composer.json but it would most likely not do any good for you.

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": [
        "laravel",
        "framework"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.2",
        "ext-fileinfo": "*",
        "ext-imagick": "*",
        "ext-openssl": "*",
        "ext-zip": "*",
        "althinect/filament-spatie-roles-permissions": "^2.2",
        "archilex/filament-filter-sets": "^3.5",
        "ariaieboy/filament-currency": "^1.2",
        "bjeavons/zxcvbn-php": "^1.3",
        "cheesegrits/filament-phone-numbers": "3.x-dev",
        "croustibat/filament-jobs-monitor": "^2.2.0",
        "filament/filament": "^3.0-stable",
        "flowframe/laravel-trend": "^0.2.0",
        "guzzlehttp/guzzle": "^7.2",
        "http-interop/http-factory-guzzle": "^1.2",
        "lab404/laravel-impersonate": "^1.7.5",
        "laravel-notification-channels/twilio": "^3.3",
        "laravel/framework": "^11.0",
        "laravel/pulse": "^1.0@beta",
        "laravel/sanctum": "^4.0",
        "laravel/scout": "^10.6",
        "laravel/tinker": "^2.8",
        "league/flysystem-ftp": "^3.0",
        "livewire/livewire": "^3.1",
        "masbug/flysystem-google-drive-ext": "^2.2",
        "meilisearch/meilisearch-php": "^1.5",
        "pxlrbt/filament-activity-log": "^1.0",
        "pxlrbt/filament-excel": "^2.3",
        "rawilk/laravel-settings": "^3.3",
        "revolution/laravel-google-sheets": "^6.2",
        "spatie/laravel-activitylog": "^4.7",
        "spatie/laravel-backup": "^8.4",
        "spatie/laravel-discord-alerts": "^1.3",
        "spatie/laravel-ray": "^1.33",
        "spatie/laravel-tail": "^4.4",
        "stechstudio/filament-impersonate": "^3.8",
        "theiconic/name-parser": "^1.2",
        "whitecube/laravel-timezones": "*"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.9",
        "fakerphp/faker": "^1.9.1",
        "jeroenzwart/laravel-csv-seeder": "^1.6",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "orangehill/iseed": "^3.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files": [
            "app/Helpers/Helpers.php",
            "app/Helpers/DebugHelper.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan filament:upgrade"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://filament-filter-sets.composer.sh"
        },
        {
            "type": "vcs",
            "url": "https://github.com/XXXX/filament-phone-numbers"
        }
    ],
    "minimum-stability": "beta",
    "prefer-stable": true
}
```

Kenneth Sese the owner of this package mentioned Anystack so I am gonna assume he is using that service to host this package.

**Comment by glaarg-robert** [comment]
Was able to solve it temporarily anyway doing the following...

**Comment by mpociot** [comment]
So the problem only exists with PHP 8.2?

**Comment by glaarg-robert** [comment]
The problem only exists with php8.3 you have to switch back to php8.2 to get around the issue.

Looking all through the Herd app I see where you can install certain versions of PHP but you can only change which PHP version per site on the Sites tab but that does not change PHP for the command line unless I am missing a different option someplace.  Or maybe I need to source a file I am not aware of to reload something?

The work around I posted above worked for me but for others if you have an easier way that would be great to post here.  I am no Herd expert so I may just be missing it.

**Comment by maximierung** [comment]
> Was able to solve it temporarily anyway doing the following...
> 
> Installed php8.2 via Herd.
> 
> ```
> rm ~/Library/Application\ Support/Herd/bin/php
> ln -s ~/Library/Application\ Support/Herd/bin/php82 ~/Library/Application\ Support/Herd/bin/php
> ```
> 
> Run the composer update or install what ever you normally are doing that is failing.
> 
> ```
> rm ~/Library/Application\ Support/Herd/bin/php
> ln -s ~/Library/Application\ Support/Herd/bin/php83 ~/Library/Application\ Support/Herd/bin/php
> ```
> 
> That will do the composer work and switch back to php8.3.

Sadly that doesn't seem to work on Windows 11. But I fixed it this way:

Run `composer install` on php8.3.

Change Herd to php8.1 (cURL 8.4.0) & run `composer install --ignore-platform-reqs`.

Then you should be fine, to change it back once all the installing is done, atleast I was.

**Comment by craigvc** [comment]
Yeh same issues on private repos

**Comment by craigvc** [comment]
The problem exists in windows also so you actually have to go to 8.1 in windows in herd (which is a big issues for my team as we have to remove half our dependencies just to install half a project, 8.2 in mac - @mpociot the issue is identified as the curl version and we need to use 3.6.16 i think it is - how can we make herd use that version?

**Comment by mpociot** [comment]
On Windows, all we do is download the official PHP binaries that php.net provides, so this feels like it's a curl issue not solved there?
We don't manually configure or deal with anything curl related on Windows

**Comment by craigvc** [comment]
> On Windows, all we do is download the official PHP binaries that php.net provides, so this feels like it's a curl issue not solved there? We don't manually configure or deal with anything curl related on Windows

Its also on mac but you can downgrade to 8.2 in mac to get around it

**Comment by mpociot** [comment]
I am currently publishing a new PHP update, which fixes this issue and will be available via the in-app updater.

**Comment by dixi83** [comment]
Is it possible the issue still persists? running Herd on Windows 11 and also facing error 23 on private repo's...

**Comment by mpociot** [comment]
This is now fixed with the latest PHP and Herd versions

**Comment by craigvc** [comment]
The issue still exists on windows 11 new install of Herd

**Comment by craigvc** [comment]
@mpociot whilst I appreciate the complexities of this, I have paid for a team licence. Half my team are on windows and all still have issues with the curl23 error. So much so many have switched to back to laragon. Is this issue getting resolved?

**Comment by mpociot** [comment]
We published a new version of Herd (1.6.1) yesterday, which updated composer to the latest version, which fixes this.

**Comment by AzGasim** [comment]
> Still facing this issue today, Herd v1.6.1 running PHP8.3.7
> 
> <img alt="image" width="725" src="https://private-user-images.githubusercontent.com/1863115/339079684-88e2332d-d1f8-45bf-a4be-8a1df3c1ab06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODg4MjgsIm5iZiI6MTcxODI4ODUyOCwicGF0aCI6Ii8xODYzMTE1LzMzOTA3OTY4NC04OGUyMzMyZC1kMWY4LTQ1YmYtYTRiZS04YTFkZjNjMWFiMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTQyMjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2NjMWRjNzI2MDQxNzI3MzdiMGQ0MmRmOTE5ZTgxODcwMzQ3NWQ0Mzg0MWExNmQyYjM2NjNkOTU3MWFkYzk2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N0aW6nqm1qZjCv8r5zpNfkUfvKxsuBAou1yUCWBrfTs">
> Had to revert back to WSL2. Any other tips?

Same problem, i tried all possible recommendations, but nothing worked, still stucked.

**Comment by chris-bkjg** [comment]
@mpociot this is still an issue with PHP8.2 and PHP8.3 on Windows 11.

**Comment by OscarKolsrud** [comment]
Can report this occured to me today on PHP 8.3.16 (Herd version 1.14.0), Windows 10 Version 22H2 (Build 19045.5371).

Happens with private composer repos. I can possibly share creds if needed to finally resolve this (Via DM ofc.)

@mpociot Sorry to @ directly, but done for attention due to closed issue.

**Comment by ChrisThompsonTLDR** [comment]
@sschlein @mechelon and @mpociot, this ticket should be reopened.  This is still an issue for many of us.

**Comment by mpociot** [comment]
So it seems like this now only happens on windows?

**Comment by archilex** [comment]
Hi @mpociot! This is Kenneth, creator of the Advanced Tables plugin for Filament. In the last 6 months (maybe more) all my support requests regarding curl23 have been exclusively from Windows users so it appears that the problem is just isolated to windows users now.

**Comment by ChrisThompsonTLDR** [comment]
@mpociot I can't speak for everyone, but it seems to be a lot of Windows users in the thread still mentioning it.  I'm available for a screenshare or whatever you guys need if you can't replicate it.

**Comment by zachiler** [comment]
Can confirm, been dealing with this issue for awhile now. The PHP version swap seems to be the only way around it on Windows. Would appreciate a response from the BeyondCode team if possible.

**Comment by sschlein** [comment]
Did you have a look at the troubleshooting section in the docs?

https://herd.laravel.com/docs/windows/troubleshooting/composer

Were mostly fighting against anti virus software here and can't fix that in Herd.

**Comment by ChrisThompsonTLDR** [comment]
@sschlein I don't have the anti-virus softwares mentioned.  Since Herd installed all of the PHP versions on my localhost, I'm curious to know why Herd was able to install PHP8.2 and I can successfully use it with composer, but Herd was not successful at installing any other PHP versions that can be used with Herd for composer.

**Comment by ashniazi** [comment]
@sschlein same issue, only using Defender, added composer stream directory (%temp%/composer) also to exclude list. On php 8.3(8.3.20), latest version of herd, every env var is correct and points to curl 8.13.0. 

Yet the
`php -i | findstr "cURL Information`

Always returns cURL Information => 8.7.0‑DEV  as it seems its baked into the binary unless I'm mistaken?

Also self-updated to latest composer, refreshed the new curl perm as well. Facing issue with pulling from private repo.

**Comment by sschlein** [comment]
Herd uses the official downloads for PHP from php.net – and PHP includes the curl extension that you see when running `php -i | findstr "cURL Information` – so we're relying on them to recompile and provide an update to make that work.
