### ISSUE TITLE
[Bug]: Not seeing Wordpress Error logs in the log file

### ISSUE THREAD

**Issue by mikemuller** [beyondcode/herd-community#767]
### Platform

macOS

### Operating system version

Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1

### PHP Version

8.2

### Bug description

When I have a fatal error in Wordpress, I'm not seeing any log being generated. This is a new install of Herd and trying to move away from Local by flywheel so I may not be looking in the right place

### Steps to reproduce

WP site throws a critical error. No log file is being saved and the log window in Herd is blank.

**Comment by sschlein** [comment]
The log window geets support for other frameworks than Laravel with the next release 🙂

Where does WordPress usually create logs?

**Comment by mikemuller** [comment]
Depends on the local setup. The log files can be stored in the wp-content folder or they can be added to the logs for the application.

Local by Flywheel for example stores the logs in a config directory for each site. There is a php error log and access log that is generated.

Having the logs be part of the general herd log would be ok. Or using the Wordpress debug functions would work too.

// Enable WP_DEBUG mode
define( 'WP_DEBUG', true );
// Enable Debug logging to the /wp-content/debug.log file
define( 'WP_DEBUG_LOG', true );
// Disable display of errors and warnings
define( 'WP_DEBUG_DISPLAY', false );
@ini_set( 'display_errors', 0 );
// Use dev versions of core JS and CSS files (only needed if you are modifying these core files)
define( 'SCRIPT_DEBUG', true );

This is how we generate logs most of time.

Mike Muller
Executive Vice President
stevens | advertising
ph: 616.942.2801
stevensinc.com
The information contained in this e-mail and any accompanying documents may be confidential, may be proprietary or otherwise legally exempt from disclosure. If you are not the intended recipient, you are hereby notified that you are not authorized to read, print, use, copy or disseminate this message, or any part thereof, or any of its attachments. If you have received this message in error, please delete this message and any attachments from your system and devices without reading the content and notify the sender of the inadvertent transmission.

**Comment by sschlein** [comment]
The log viewer will automatically pick up the wo-content folder but you can also add a custom driver to get the others 🙂

**Comment by mikemuller** [comment]
Any ETA on the new version?

Mike Muller
Executive Vice President
stevens | advertising
ph: 616.942.2801
stevensinc.com
The information contained in this e-mail and any accompanying documents may be confidential, may be proprietary or otherwise legally exempt from disclosure. If you are not the intended recipient, you are hereby notified that you are not authorized to read, print, use, copy or disseminate this message, or any part thereof, or any of its attachments. If you have received this message in error, please delete this message and any attachments from your system and devices without reading the content and notify the sender of the inadvertent transmission.

**Comment by sschlein** [comment]
Likely next week but I can publish a beta build early if we decide to push back the official release. 

I'll share it here!

**Comment by mpociot** [comment]
This is now fixed in Herd 1.7.0

**Comment by andrewjmead** [comment]
I'm running Herd 1.9.1, but I still don't see error logs anywhere except `php-fpm.log` for a WordPress site.

I was hoping to see them in `wp-content/debug.log` or in the Laravel logs panel, but both are empty.

I was able to recreate this on my main machine and on a separate wiped laptop with nothing but Herd installed.

**Comment by shivapoudel** [comment]
@mpociot For WordPress context, still an issue. Default `wp-content/debug.log` is not respected. Relevant tickets:

https://github.com/beyondcode/herd-community/issues/266

> Errors should be logged in wp-content/debug.log within the folder for that site, but they are logged in the global log at /Users/myusername/Library/Application Support/Herd/Log/php-fpm.log.

This ticket itself is the replicable step.

https://github.com/beyondcode/herd-community/issues/134

> You can just change the FPM config file to your liking in this case 👍

Most of us understand, but not the whole WordPress community, my friend :)
