### ISSUE TITLE
[Bug]: Install NVM button is not doing anything

### ISSUE THREAD

**Issue by Mavv3006** [beyondcode/herd-community#787]
### Platform

macOS

### Operating system version

macOS Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1

### PHP Version

8.3

### Bug description

Currently I do not have `nvm` installed because I wanted to use the nvm which comes with the Herd installation.

But when opening the Node menu in Herd the install nvm button appears. But after clicking it, it does nothing

Also refer to https://github.com/beyondcode/herd-community/discussions/492

### Steps to reproduce

prerequisites:
1. do not have nvm installed
2. do not have herd installed

steps: 
1. install herd
3. open herd and navigate to the Node menu
4. click the appearing "install nvm" button
5. => nothing happens

**Comment by Mavv3006** [comment]
<img width="1022" alt="Bildschirmfoto 2024-06-10 um 09 51 51" src="https://github.com/beyondcode/herd-community/assets/52504463/89aac541-70a9-4e3f-8d09-e0f7f3195ec8">

**Comment by Mavv3006** [comment]
FYI: After the installation of Herd 1.7.1 (update from 1.6.1) nvm has been installed on my machine.

note: This is not a resolution of this issue, but rather a notice to find the root cause.

**Comment by jingidy** [comment]
I have the same problem except I already have an nvm on my machines, I unchecked the "install node using nvm" when installing herd, but now herd says unknown node version for all sites and the button to install does nothing.

**Comment by davidbarker** [comment]
### Fix
Temporarily remove the contents of your `~/.zshrc` (or similar) file if you've customised it.

### Explanation
I've had this exact issue ever since I first started to use Herd. However, I jut noticed this in the Herd documentation (https://herd.laravel.com/docs/1/advanced-usage/node-versions):

> Herd parses command output to determine your current Node.js version. If it can't parse the output because there is output that it doesn't understand, or you are using an unsupported shell, it displays Unknown for your node version in the sites list. Herd is an opinionated development environment that relies on bash or zsh and other shells lead to errors.

It made me think — perhaps my `~/.zshrc` file is causing the output to be unreadable to Herd. I deleted the contents of the `~/.zshrc` file and the Install NVM button worked immediately!

Herd adds a couple of lines to the `~/.zshrc` file, so I just pasted the original contents above it.

**Comment by alexanderzeillinger** [comment]
Similar issue with v1.8.0 on Windows - when clicking the button it flickers shortly showing the installed versions but then the button returns.

**Comment by lesaff** [comment]
I've updated my Herd install to v1.8.0 and the Node install works now. Thanks!

**Comment by mpociot** [comment]
I think this is now fixed in the latest versions of Herd 🤞 
Hasn't happen in a while now

**Comment by alexanderzeillinger** [comment]
I have 1.9.0 installed and the problem still exists, so this can be opened again.

**Comment by zc632995195** [comment]
Same on Mac with 1.9.1, I tried the above fix (remove my ~/.bash_profile ) --> I do see Herd exports some env vars there, but sill not work.. 

I also tried to install via CLI as mentioned in doc: https://herd.laravel.com/docs/1/advanced-usage/node-versions (local have node for app), but on starting up the Herd still cannot recognize it and shows no nvm version..

**Comment by greifbar** [comment]
Same here - fresh installed 1.11.0 (Build 33) and the button doesn't do anything :(

**Comment by Blinks44** [comment]
yep, 1.11.2, same behavior, clicks do nothing

**Comment by Moibe** [comment]
Still happening in windows 10 in herd version 1.13.0

**Comment by markomitranic** [comment]
Can confirm still happens in Macos 15.3 and freshly installed Herd 1.14.1

**Comment by mpociot** [comment]
@markomitranic which shell do you use? Fish shell by any chance?

**Comment by markomitranic** [comment]
@mpociot no, bash for life <3

**Comment by BWBama85** [comment]
This is happening for me on MacOS 15.4 and Herd 1.19.0

**Comment by ovvessem** [comment]
Based on my fresh installation of Herd it seems that the file `nvmnvm.sh` is misplaced in the Herd/config/ directory where it might be Herd/config/nvm/nvm.sh as this is the file that is called in the `.zshrc` for the Herd injected NVM configuration

export NVM_DIR="/Users/[username]/Library/Application Support/Herd/config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

**Comment by petarcar** [comment]
Win 11 pro, Herd 1.28.0 I still experience quick flicker on click of a button but noth8ing happens after.

**Comment by svenluijten** [comment]
This started happening to me after updating Herd to the latest version (1.28.0). It worked fine previously, `npm`, `node`, and `nvm` commands were available. Then, after updating, the commands were _gone_. 

@ovvessem's comment from above led me to the solution that worked for me. Running `~/Library/Application Support/Herd/config/nvm/install.sh` manually yielded the following result:

```
➜  nvm ./install.sh
=> Downloading nvm from git to '/Users/svenluijten/Library/Application Support/Herd/config/nvm'
=> Initialized empty Git repository in /Users/svenluijten/Library/Application Support/Herd/config/nvm/.git/
=> Compressing and cleaning up git repository

=> nvm source string already in /Users/svenluijten/.zshrc
=> Appending bash_completion source string to /Users/svenluijten/.zshrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/Library/Application Support/Herd/config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

As it turns out, Herd assumes you store your dotfiles configuration in `~/.zshrc` (or your shell's equivalent). I store mine in the XDG-compliant `~/.config/zsh/.zshrc`, which causes the nvm config it appends to `~/.zshrc` to do _nothing_, and my shell doesn't know about its existence.

> [!IMPORTANT]
> Appending the last 3 lines from the code snippet above to `~/.config/zsh/.zshrc` (or whatever your `$ZDOTDIR/.zshrc` resolves to) fixes the issue I was facing.

---

@mpociot the (ideal) solution for this would be to append the lines where it sets the `NVM_DIR`, runs `nvm.sh`, and loads the bash completion to `$ZDOTDIR/.zshrc` instead of hardcoding it to append to `~/.zshrc` 😄
